name: powernet
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 5.0.2+31

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  dialog_flowtter:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  http: ^1.1.2
  convex_bottom_bar: ^3.0.0
  share_plus: ^7.2.1
  crypto: ^3.0.2
  convert: ^3.0.2
  plugin_platform_interface: ^2.1.2
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.2
  flutter_bloc: ^8.0.1
  awesome_dialog: ^3.0.2
  shared_preferences: ^2.0.15
  country_code_picker: ^3.0.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  intl: ^0.18.1
  provider: ^6.0.3
  lottie: ^2.0.0
  animator: ^3.2.0
  skeletons: ^0.0.3
  path_provider: ^2.0.11
  path: ^1.8.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.1.7
  permission_handler: ^11.1.0
  flutter_polyline_points: ^2.0.0
  location: ^5.0.3
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.1
  google_sign_in: ^6.1.6
  geocoding: ^2.0.4
  flutter_svg: ^2.0.9
  flutter_facebook_auth: ^6.0.3
  firebase_auth: ^4.1.2
  flutter_local_notifications: ^16.2.0
  firebase_messaging_web: ^3.2.6
  firebase_messaging_platform_interface: ^4.2.6
  firebase_core_platform_interface: ^5.0.0
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  equatable: ^2.0.3
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.5
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.3
  photo_view: ^0.14.0
  flutter_typeahead: ^5.0.1
  image_to_byte: ^1.0.0
  jwtson: ^1.0.7
  font_awesome_flutter: ^10.1.0
  rive: ^0.11.17
  velocity_x: ^4.1.2
  connectivity: ^3.0.6
  carousel_slider: ^4.1.1
  store_redirect: ^2.0.1
  webview_flutter: ^4.4.2
  toggle_switch: ^2.0.1
  expandable: ^5.0.1
  expandable_widgets: ^1.0.3+1
  clipboard: ^0.1.3
  printing: ^5.9.3
  pdf: ^3.8.4
  blue_thermal_printer: ^1.2.3
  searchable_paginated_dropdown: ^1.2.0
  dotted_decoration: ^2.0.0
  custom_info_window: ^1.0.1
  custom_date_range_picker: ^1.0.6
  syncfusion_flutter_charts: ^23.2.6
  skeleton_animation: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/ic_foreground.png"

  # icons_launcher: ^1.2.1

  # icons_launcher:
  #   icons_launcher:
  #   image_path: "assets/logos/ic_logo_border.png"
  #   platforms:
  #     android:
  #       enable: true
  #       image_path: "assets/logos/ic_logo_border.png"
  #       adaptive_background_image: "assets/logos/ic_background.png"
  #       adaptive_foreground_image: "assets/logos/ic_foreground.png"
  #       adaptive_round_image: "assets/logos/ic_logo_round.png"
  #     ios:
  #       enable: true
  #       image_path: "assets/logos/ic_logo_rectangle.png"

  # flutter_icons:
  #   image_path_android: "assets/logos/ic_logo_border.png"
  #   image_path_ios: "assets/logos/ic_logo_rectangle.png"
  #   image_path_macos: "assets/logos/ic_logo_border.png"
  #   image_path_windows: "assets/logos/ic_logo_border.png"
  #   image_path_linux: "assets/logos/ic_logo_border.png"
  #   image_path_web: "assets/logos/ic_logo_border.png"
  #   adaptive_icon_background: "assets/logos/ic_background.png" # only available for Android 8.0 devices and above
  #   adaptive_icon_foreground: "assets/logos/ic_foreground.png" # only available for Android 8.0 devices and above
  #   adaptive_icon_round: "assets/logos/ic_logo_round.png" # only available for Android 8.0 devices and above #! (Optional)
  #   remove_alpha_ios: true
  #   remove_alpha_macos: false
  #   android: true
  #   ios: true
  #   macos: false
  #   windows: false
  #   linux: false
  #   web: false
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animation/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/AvenirNext-Regular.ttf
